/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppMain {}
  interface AppPageOne {}
  interface AppPageTwo {}
  interface AppRoot {}
}

declare global {


  interface HTMLAppMainElement extends Components.AppMain, HTMLStencilElement {}
  var HTMLAppMainElement: {
    prototype: HTMLAppMainElement;
    new (): HTMLAppMainElement;
  };

  interface HTMLAppPageOneElement extends Components.AppPageOne, HTMLStencilElement {}
  var HTMLAppPageOneElement: {
    prototype: HTMLAppPageOneElement;
    new (): HTMLAppPageOneElement;
  };

  interface HTMLAppPageTwoElement extends Components.AppPageTwo, HTMLStencilElement {}
  var HTMLAppPageTwoElement: {
    prototype: HTMLAppPageTwoElement;
    new (): HTMLAppPageTwoElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'app-main': HTMLAppMainElement;
    'app-page-one': HTMLAppPageOneElement;
    'app-page-two': HTMLAppPageTwoElement;
    'app-root': HTMLAppRootElement;
  }
}

declare namespace LocalJSX {
  interface AppMain {}
  interface AppPageOne {}
  interface AppPageTwo {}
  interface AppRoot {}

  interface IntrinsicElements {
    'app-main': AppMain;
    'app-page-one': AppPageOne;
    'app-page-two': AppPageTwo;
    'app-root': AppRoot;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-main': LocalJSX.AppMain & JSXBase.HTMLAttributes<HTMLAppMainElement>;
      'app-page-one': LocalJSX.AppPageOne & JSXBase.HTMLAttributes<HTMLAppPageOneElement>;
      'app-page-two': LocalJSX.AppPageTwo & JSXBase.HTMLAttributes<HTMLAppPageTwoElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
    }
  }
}


